# Generated by Django 5.0.7 on 2024-08-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('modified_at',)},
        ),
    ]
