# Generated by Django 5.0.7 on 2024-08-03 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_note_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-modified_at',)},
        ),
    ]
